реализация оценок
Mithrilin/java-filmorate pull request #22
Opened 2024-02-12 13:35 UTC by Mithrilin

2024-02-14 15:08 UTC, mysosnovskaya requested changes
В ПРе как будто две задачи: про оценки и про режиссеров. Было бы хорошо, если бы режиссеры были оформлены отдельно. Я ревьювила часть с оценками. Конечно, в основном алгоритм. Ему не хватает ясности. Для этого нужно разбить код на методы, дать понятные названия переменным и методам, добавить краткое описание алгоритма.

2024-02-14 15:08 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        for (Map.Entry<Integer, HashMap<Integer, Double>> users : diff.entrySet()) {
Поиск нужного пользователя я бы тоже в отдельный метод вынесла

2024-02-14 15:08 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        for (Map.Entry<Integer, Double> e : recommendationMap.entrySet()) {
А давай это через стримы попробуем сделать?)

2024-02-18 19:39 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +                        @RequestParam String mark) {
Исправил.

2024-02-18 19:39 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getFilmsByDirectorId(@PathVariable int directorId, @RequestParam String sortBy) {
Перенёс

2024-02-18 19:39 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Double mark;
Изменил

2024-02-18 19:40 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        jdbcTemplate.query(allUsersMarksSql, (RowMapper<Film>) (rs, rowNum) -> {
Вынес

2024-02-18 20:30 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        Map<Integer, Double> userMark = new HashMap<>();
Тип double появился из-за особенностей запроса. У меня там рейтинг получался целочисленным. Сейчас разобрался, как это исправить)

2024-02-18 20:38 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        String allUsersMarksSql =
Вынес

2024-02-18 20:40 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
>          Map<Integer, Film> filmMap = new HashMap<>();
Исправил

2024-02-18 20:43 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +                // ид пользователя
Исправил

2024-02-18 20:44 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        int userMinDiff = 0;
Исправил

2024-02-18 20:45 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +                    int newMatch = match.get(userId) + 1;
Исправил

2024-02-19 11:15 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +                if (e.getValue() > 5) {
Исправил

2024-02-20 07:43 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        Map<Integer, HashMap<Integer, Double>> allUsersMarks = new HashMap<>();
userMark убрал

2024-02-20 07:44 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        Map<Integer, HashMap<Integer, Double>> diff = new HashMap<>();
исправил

2024-02-20 07:44 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
>      public List<Film> getRecommendations(int id) {
переименовал

2024-02-20 17:41 UTC, closed without merging