Add marks
Mithrilin/java-filmorate pull request #23
Opened 2024-02-20 17:48 UTC by Mithrilin

2024-02-21 14:08 UTC, mysosnovskaya requested changes

2024-02-21 14:08 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        return filmsIdWithPositiveMark.isEmpty();
Странно, что мы уже нашли id фильмов, которые можно порекомендовать, а потом про них забыли. Как будто бы нужно возвращать как раз filmsIdWithPositiveMark. Тогда sql запрос будет проще (по факту просто получения фильма по id, а сейчас там зачем-то оценка опять проверяется)

2024-02-21 14:08 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +            for (Integer e : users.getValue().values()) {
Через стрим?)

2024-02-21 14:08 UTC, mysosnovskaya commented on src/test/java/ru/yandex/practicum/filmorate/dao/impl/RecommendationsTest.java
> +        filmDbStorage.addMark(filmsId.get(0), usersId.get(0), 1);
Страшненько выглядит, конечно. Но я уже писала, чтобы было лучше, нужны моки, которые мы будем проходить позже. А пока получилась хорошая объемная работа по тестированию)

2024-02-22 08:37 UTC, Mithrilin commented on src/test/java/ru/yandex/practicum/filmorate/dao/impl/RecommendationsTest.java
> +        filmDbStorage.addMark(filmsId.get(0), usersId.get(0), 1);
Спасибо)

2024-02-22 08:40 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +            for (Integer e : users.getValue().values()) {
Переделал

2024-02-22 08:46 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        for (Map.Entry<Integer, HashMap<Integer, Integer>> users : userIdToFilmIdWithMark.entrySet()) {
Переименовал

2024-02-22 10:05 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        Map<Integer, Film> filmMap = new HashMap<>();
1. Честно говоря, я и сам не очень помню почему так получилось...🫣 Наверное я вносил изменения какие-то и надобность в этой мапе снаружи отпала. Исправил

2024-02-22 12:34 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        Integer userIdWithMinDiff = minDiffCountAndUserIdGetter(userIdToFilmIdWithDiff,
Исправил)

2024-02-22 12:37 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        differencesAndMatchesBetweenUsersGetter(userIdToFilmIdWithDiff,
спасибо за подсказку, так и правда логичнее)

2024-02-25 11:53 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmServiceImpl.java
> +            throw new ConstraintViolationException("Параметр поиска не определён.", null);
Исправил

2024-02-25 11:54 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +        differencesAndMatchesBetweenUsersGetter(userIdToFilmIdWithDiff,
исправил

2024-02-25 11:55 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +    private void differencesAndMatchesAdder(Map.Entry<Integer, HashMap<Integer, Integer>> users,
исправил

2024-02-25 13:40 UTC, Mithrilin commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbStorage.java
> +        Map<Integer, Film> filmMap = new HashMap<>();
Исправил

2024-02-27 12:49 UTC, mysosnovskaya requested changes
Осталось чуть-чуть :)

2024-02-27 12:49 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDao.java
> +    List<Film> getRecommendations(List<Integer> userIdWithMinDiff);
Неправильное название для параметра, это же айди фильмов?
И эти методы, конечно, должны быть в FilmDao, т.к. с пользователями они фактически и не работают. На мой взгляд, перенести код несложно, так что предлагаю это сделать)

2024-02-27 12:49 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +            for (Map.Entry<Integer, Genre> e : filmIdToGenre.entrySet()) {
Попробуем через стрим?

2024-02-27 12:49 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/UserDbStorage.java
> +            for (Map.Entry<Integer, Director> e : filmIdToDirector.entrySet()) {
Стрим?

2024-02-27 12:49 UTC, mysosnovskaya commented on src/main/java/ru/yandex/practicum/filmorate/dto/params/MarksParams.java
> +public class MarksParams {
Я бы вообще дала такому классу право на существование как полноценную модель, тем более есть соответствующая таблица в базе данных) Назвала бы Mark или FilmMark

2024-02-29 15:17 UTC, mysosnovskaya approved these changes

2024-02-29 15:57 UTC, merged